### ISSUE TITLE
Request: Image diffing for QA purposes

### ISSUE THREAD

**Issue by smartin015** [jneilliii/OctoPrint-BedReady#16]
Some folks that use my Continuous Print plugin are running print farms that churn out parts continuously, and QA was mentioned as a factor when managing inventory (see https://github.com/smartin015/continuousprint/issues/57 for context).

BedReady already enables image diff checks in OctoPrint, so I was wondering if it could be extended to perform an "initial QA" of parts after they complete. This would allow CPQ to automatically retry parts that fail QA enough that it's visible by camera, which would in turn save operator time and effort.

I'm imagining two changes:

1. Allow storing several (named/tagged) images. This could be done in the plugin_data folder.
2. Accept requests from other OctoPrint plugins to perform a diff against one of the named images, or the "default" image if no name is given. I was considering spoofing a call to your `process_at_command()` so as not to use any internal / likely changed methods.

I realize this is similar to #4  - happy to merge into that discussion if it's similar enough. Thanks!

**Comment by jneilliii** [comment]
I'd be willing to implement plugin helpers to allow your plugin to submit the image paths to compare and respond with the comparison result percentage. Not sure when I'd be able to get to making those changes though. If you wanted to submit a PR implementing that approach it would be welcomed if you wanted it sooner.

**Comment by smartin015** [comment]
Neat - I'll be occupied the next few weeks, so no hurry on implementation. I'll post here in advance of a PR if/when I find time to send one your way :)

**Comment by smartin015** [comment]
FYI - I'm starting to poke at this. Will hopefully have the first step of "allow multiple reference images" in a PR for you in a couple days.

**Comment by smartin015** [comment]
Okay - #18 is ready for review. Thanks for helping to upstream this!

**Comment by jneilliii** [comment]
No, thank you for the PR. That's a huge help to me with so many plugins to maintain.

**Comment by smartin015** [comment]
One more PR for you for part 2 :) 

#19
