### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by montyfert** [jneilliii/OctoPrint-BedReady#17]
i tried installing OctoPrint-BedReady but it couldnt it was showing 
octoprint Building wheel for opencv-python-headless (PEP 517): still running.
octoprint Building wheel for opencv-python-headless (PEP 517): still running
octoprint Building wheel for opencv-python-headless (PEP 517): still running

thanks 
martin

**Comment by jneilliii** [comment]
it can take a considerable amount of time to install if that module has to compile. you just have to let it go until it completes. it is stating it's still running.

**Comment by montyfert** [comment]
thank you 
martin
