### ISSUE TITLE
OctoPi 1.0.0 Missing libopenblas

### ISSUE THREAD

**Issue by sh0x1337** [jneilliii/OctoPrint-BedReady#21]
[octoprint (1).log](https://github.com/jneilliii/OctoPrint-BedReady/files/13770123/octoprint.1.log)

See my log in attachment, here are serveral errors and he skips the @BEDREADY Part in the gcode because of errors....

Also the Test Reference button in the Settings does only make an http 500 error:

![image](https://github.com/jneilliii/OctoPrint-BedReady/assets/50083218/aecd289c-5366-4fa3-9843-3371475ebcea)

**Comment by jneilliii** [comment]
Yeah, I'm not quite sure what's happened in your pi instance. I just installed on the latest OctoPi 1.0.0 image and the plugin did give initial errors, but after installing missing system dependency all worked as expected. Can you run the following command for me in SSH and provide the results?

```
/home/admin/oprint/bin/pip freeze | grep numpy
```

**Comment by sh0x1337** [comment]
![image](https://github.com/jneilliii/OctoPrint-BedReady/assets/50083218/541829e1-cb37-45aa-8602-69ff45dc1000)

**Comment by sh0x1337** [comment]
i will try to reinstall my octoprint and start from beginning, maybe its any other plugin that causes this errors....btw which Raspberry Version you used? i use Raspberry Pi 4

Update 1:

After completly fresh installation:

![image](https://github.com/jneilliii/OctoPrint-BedReady/assets/50083218/e82e8172-1991-4877-856c-88c1b89cc7e0)

Update 2:
Here Fresh log with fresh installation and no other plugins running only standard ones!

[octoprint (9).log](https://github.com/jneilliii/OctoPrint-BedReady/files/13778357/octoprint.9.log)

Update 3:

Tested with Raspberry Pi 3B+ fresh installed

![image](https://github.com/jneilliii/OctoPrint-BedReady/assets/50083218/9fe768fc-d408-4199-8e1f-9de71f7543df)

Update 4:

Log file from Raspberry Pi 3B+:

[octoprint (10).log](https://github.com/jneilliii/OctoPrint-BedReady/files/13778568/octoprint.10.log)


Always same Problem:

`2023-12-27 12:29:17,652 - octoprint.plugins.bedready - INFO - check_bed with reference reference_2023-12-27T12:27:40.699Z.jpg (threshold 0.98)
2023-12-27 12:29:17,652 - octoprint.settings - WARNING - DeprecationWarning: Detected access to deprecated settings path ['webcam', 'snapshot'], returned value is derived from compatibility overlay. Please use the webcam system introduced with 1.9.0, this compatibility layer will be removed in a future release.
2023-12-27 12:29:17,704 - octoprint.plugins.bedready - INFO - Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.`

Also Output for Raspberry Pi 3B+:

![image](https://github.com/jneilliii/OctoPrint-BedReady/assets/50083218/17c2d365-46f3-4677-86ca-a94d614f329f)

**Comment by jneilliii** [comment]
Thanks Charlie, was going to get around to that.

@sh0x1337 is it still the same error after the refresh in octoprint.log or are you getting an openblas error like I did?

**Comment by sh0x1337** [comment]
`sudo apt install libopenblas-dev`

this fixed my issue and finally it working!

![image](https://github.com/jneilliii/OctoPrint-BedReady/assets/50083218/9f39cd33-6b00-44b1-9360-4421a264dcda)

**Comment by jneilliii** [comment]
yep, that was the error I was getting, and why I was wondering if your were getting the same error. pinning issue.
