### ISSUE TITLE
Not taking reference photo

### ISSUE THREAD

**Issue by Afalti** [jneilliii/OctoPrint-BedReady#5]
when I go to take the reference photo, it lets me push the button, but then it just continuously gives me the spinning loading sign. I am not using a camera that is connected to the pi that is running octoprint, but rather using a webcam server as my stream. Any help is greatly appreciated.

**Comment by jneilliii** [comment]
The plugin requires a snapshot URL to function properly. That can be configured in OctoPrint's Webcam & Timelapse settings.

**Comment by jneilliii** [comment]
You may also need to check octoprint.log or the browser's developer tools (console tab) for any potential errors during the process.

**Comment by Afalti** [comment]
so I checked octoprint.log, and it didn't show anything weird, so I then checked the snapshot URL again, and used the test button, and it said that it couldn't retrieve the snapshot URL, and to double check the URL, but it is the same URL as the webcam stream and I can access it, and OctoPrint can access it since it is showing the stream perfectly fine. do you know what could be causing this?

**Comment by jneilliii** [comment]
The two URLs should not be exactly the same. What are you using to stream with? The default for an octopi image (mjpgstreamer) would be `http://127.0.0.1:8080/?action=snapshot`

**Comment by Afalti** [comment]
I am using a webcam server for the stream since my picamera broke, and my pi doesn't like the USB webcam that I have, so I made a webcam server.

**Comment by Afalti** [comment]
The service I am using is motion

**Comment by jneilliii** [comment]
You need to find out from the webcam server's docs what a valid **snapshot** URL would be. The problem with an mjpg stream URL is that the image never finishes downloading as it is continuously refreshed.

**Comment by jneilliii** [comment]
Quick search seems to indicate that `http://ip:8080/0/action/snapshot` might work...

**Comment by Afalti** [comment]
so I tried using http://ip:8081/0/action/snapshot since the stream is located at http://ip:8081, and it still says that is can't retrieve snapshot URL

**Comment by Afalti** [comment]
I then tried doing http://ip:8080/0/action/snapshot and it still is failing

**Comment by jneilliii** [comment]
I haven't used motion in some time, but I think MotionEyeOS had a place in the interface to tell you what this is. Otherwise, you'll have to mess with config files I suspect. I found this which may be related.

https://github.com/Motion-Project/motion/issues/735#issuecomment-398932057

**Comment by Afalti** [comment]
I've looked through this, but it seems that that problem was solved in an update, and I have a newer version than that update. So either it's something else, or I'm just not seeing something or being stupid.

**Comment by Afalti** [comment]
I have found that Motion seems to be taking the snapshot when I tell it to, but it seems that octoprint still can't get it. would this be caused by the webcam server not being able to send the snapshot? or a communication issue?

**Comment by jneilliii** [comment]
so the way the plugin works is it uses the snapshot URL in OctoPrint's settings to request the snapshot. If the URL responds then it saves that snapshot into the plugin's data folder. If it's not saving the snapshot then it's either an issue with the plugin requesting the snapshot or the motion side not providing it. If you are actively pressing a button to take a snapshot that won't work with the plugin, because it has to be made available via a direct URL without interaction.

**Comment by Afalti** [comment]
found the problem, but not an easy solution. Motion doesn't provide access to it's stored snapshots or movies, but will accept a command to take them. I will take this to the motion forums. Thanks for your help!
