### ISSUE TITLE
Cancel rather than pause on failure

### ISSUE THREAD

**Issue by bnorick** [jneilliii/OctoPrint-BedReady#7]
Is it possible to support cancel rather than pause on failure? A simple checkbox to enable something like this would be nice, as I don't want my custom GCODE which executes on resuming from pause to execute when that pause was actually just a bed ready failure. As it is, I can't use the plugin despite thinking it's great.

Thanks!

**Comment by jneilliii** [comment]
Added an Action option with the above commit and is part of release version 0.1.5. There is a weird issue that I believe to be an internal bug with OctoPrint that when the print is cancelled the state panel doesn't update and the percentage, time remaining, etc. still show information and aren't getting reset. The print is actually getting cancelled though and the printer does get reset to an operational state which allows starting the print again.
