### ISSUE TITLE
API / Helpers for interaction with other plugins

### ISSUE THREAD

**Issue by RoboMagus** [jneilliii/OctoPrint-BedReady#9]
For some plugins, in my example [Preheat Helper](https://github.com/RoboMagus/OctoPrint-PreheatHelper), it would be nice to be able to query BedReady if the bed is empty. E.g. in my case it might be a nice addition to not preheat the bed to 100 degrees when a previous PLA print might still be left on the bed.

I would envision using [plugin helpers](https://docs.octoprint.org/en/master/plugins/helpers.html) for this. Perhaps implement this as an async method. 

I'd love to hear your thoughts on this :)

**Comment by jneilliii** [comment]
I added a helper in the last release for other plugin's to utilize. The API itself is there already for testing the snapshot as well.

**Comment by jneilliii** [comment]
the helper command is check_bed and either returns Nothing on error or the following data structure (same for API).

{"bed_clear": False "similarity": 0.8234}

**Comment by jneilliii** [comment]
Apologies, the test API actually returns the following structure: {"test_image": url_for_captured_test_image, "similarity": 0.8234}

**Comment by RoboMagus** [comment]
Ah I should have checked for updates before posting this issue then :)
I had the idea when you were at v. 0.1.3.
Apologies for the noise. Great work @jneilliii!
